export function StylesRegister() {
    return {
        container: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '20px',
            boxSizing: 'border-box',
        },
        card: {
            backgroundColor: 'rgb(207, 208, 250)',
            borderRadius: '15px',
            padding: '30px',
            width: '100%',
            maxWidth: '800px',
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
        },
        title: {
            fontSize: '28px',
            color: '#1E3A5F',
            marginBottom: '20px',
            textAlign: 'center',
        },
        columns: {
            display: 'flex',
            gap: '20px',
            flexWrap: 'wrap',
            justifyContent: 'space-between',
        },
        column: {
            flex: 1,
            minWidth: '280px',
            display: 'flex',
            flexDirection: 'column',
        },
        label: {
            marginTop: '10px',
            marginBottom: '5px',
            fontWeight: 'bold',
            color: '#1E3A5F',
            fontSize: '14px',
        },
        input: {
            padding: '10px',
            borderRadius: '6px',
            border: '1px solid #ccc',
            fontSize: '14px',
            backgroundColor: '#fff',
            outline: 'none',
            color: '#1E3A5F',
            width: '100%',
            boxSizing: 'border-box',
        },
        select: {
            padding: '10px',
            borderRadius: '6px',
            border: '1px solid #ccc',
            fontSize: '14px',
            backgroundColor: '#fff',
            color: '#1E3A5F',
            width: '100%',
        },
        buttonContainer: {
            marginTop: '30px',
            display: 'flex',
            justifyContent: 'center',
        },
        button: {
            padding: '12px 24px',
            backgroundColor: '#1E3A5F',
            color: '#fff',
            border: 'none',
            borderRadius: '8px',
            fontWeight: 'bold',
            fontSize: '16px',
            cursor: 'pointer',
            outline: 'none',
        },
        buttonHover: {
            backgroundColor: '#16324F',
        },
        loginRedirect: {
            marginTop: '20px',
            textAlign: 'center',
            color: '#1E3A5F',
            fontSize: '14px',
        },
        link: {
            color: '#E74C3C',
            textDecoration: 'underline',
            cursor: 'pointer',
            fontWeight: 'bold',
            marginLeft: '4px',
        },
        inputContenedor: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            width: '100%',
            backgroundColor: '#fff',
            border: '1px solid #B0B0B0',
            borderRadius: '6px',
            padding: '0 10px',
            boxSizing: 'border-box',
        },
        inputPassword: {
            flexGrow: 1,
            border: 'none',
            backgroundColor: '#fff',
            outline: 'none',
            padding: '0 10px',
            color: '#1E3A5F',
            fontSize: '16px',
        },
        botonMostrarContrasena: {
            background: 'none',
            border: 'none',
            cursor: 'pointer',
            fontSize: '14px',
            color: '#1E3A5F',
            outline: 'none',
        }
    };
}
  