export function StylesLogin() {
    return {
        contenedorEstilo: {
            fontFamily: 'Arial, sans-serif',
            margin: 0,
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            width: '100%',
            boxSizing: 'border-box',
            color: 'with',
        },
        contenidoEstilo: {
            textAlign: 'center',
            margin: '5%',
            height: 'auto',
            width: '800px',
            backgroundColor: 'rgb(207, 208, 250)',
            borderRadius: '20px',
            padding: '20px',
            boxSizing: 'border-box',
            boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
        },
        izquierdaEstilo: {
            textAlign: 'left',
            minHeight: '500px',
            color: '#FFFFFF',
            marginLeft: '5%',
            marginTop: '2%',
            width: '50%',
        },
        imagenEstilo: {
            width: '46%', 
        },
        tituloEstilo: {
            fontSize: '36px',
            color: '#1E3A5F',
            marginBottom: '0px',
        },
        parrafoEstilo: {
            fontSize: '18px',
            color: '#1E3A5F',
            marginBottom: '20px',
            marginTop: '10px',
        },
        inputEstilo: {
            flexGrow: 1,
            border: 'none',
            backgroundColor: 'transparent',
            outline: 'none',
            padding: '12px 0',
            color: '#1E3A5F',
            fontSize: '16px',
        },
        contenedorBotonLogin: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            marginTop: '2%',
        },
        botonLogin: {
            backgroundColor: '#005227',
            color: '#fff',
            border: 'none',
            borderRadius: '6px',
            cursor: 'pointer',
            width: '50%',
            fontFamily: 'Arial, sans-serif',
            fontWeight: 'bold',
            textDecoration: 'none',
            display: 'block',
            margin: 'auto',
            padding: '0.6em 1.2em',
            fontSize: '1em',
            transition: 'border-color 0.25s',
            outline: 'none',
        },
        botonLoginHover: {
            backgroundColor: '#003f1e',
        },
        recuperarContrasena: {
            marginTop: '3%',
            textAlign: 'center',
            color: '#E63946',
            fontSize: '14px',
            cursor: 'pointer',
        },
        imagenPrincipalEstilo: {
            width: 'auto',
            maxHeight: '180px',
            // filter: 'brightness(50%)',
        },
        botonContrasena: {
            position: 'absolute',
            right: '7%',
            top: '60%',
            transform: 'translateY(-50%)',
            background: 'none',
            border: 'none',
            cursor: 'pointer',
            fontSize: '16px',
            color: '#1E3A5F',
            outline: 'none',
        },
        labelEstilo: {
            display: 'block',
            textAlign: 'left',
            width: '80%',
            margin: '10px auto 5px auto',
            fontSize: '14px',
            color: '#1E3A5F',
            fontFamily: 'Arial, sans-serif',
        },
        inputContenedor: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            width: '80%',
            margin: '0 auto 2% auto',
            backgroundColor: '#F5F5F5',
            border: '1px solid #B0B0B0',
            borderRadius: '6px',
            padding: '0 10px',
            boxSizing: 'border-box',
        },
        inputContrasena: {
            flexGrow: 1,
            border: 'none',
            backgroundColor: 'transparent',
            outline: 'none',
            padding: '12px 0',
            color: '#1E3A5F',
            fontSize: '16px',
        },
        botonMostrarContrasena: {
            background: 'none',
            border: 'none',
            cursor: 'pointer',
            fontSize: '14px',
            color: '#1E3A5F',
            outline: 'none',
        },
        contenedorImagenPrincipal: {
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: '20px',
        },
        registroTexto: {
            marginTop: '20px',
            fontSize: '14px',
            color: '#1E3A5F',
            textAlign: 'center',
        },
        registroEnlace: {
            color: '#E74C3C',
            fontWeight: 'bold',
            textDecoration: 'underline',
            marginLeft: '4px',
            cursor: 'pointer',
        },
    };
}
  